baseURL: /
languageCode: en-us
title: Prosper Social Finance | UK’s first student-led SRI fund
theme: hugo-fresh
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: A student run socially responsible investment fund
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/logo-full.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Challenging perceptions, financing change
    # Hero subtitle (optional)
    subtitle: The UK’s first student run socially responsible investment fund
    # Button text
    buttontext: Join us
    # Where the main hero button links to
    buttonlink: "/join-us"
    # Hero image (from static/images/___)
    image: illustrations/graph3.png
    # Footer logos (from static/images/logos/clients/___.svg)
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: About
    sublinks:
    - title: Overview
      url: /about
    - title: Mission & Values
      url: /mission
    - title: Our Team
      url: /team
  - title: Investments
    sublinks:
    - title: Our Philosophy
      url: /philosophy
    - title: Our Strategy
      url: /strategy
  - title: Social Impact
    sublinks:
    - title: Overview
      url: /social-impact
    - title: Community Engagement
      url: /community-engagement
  - title: Our Programmes
    sublinks:
    - title: Programmes Overview
      url: /programmes-overview
    - title: Analysts
      url: /training
    - title: Senior Analysts
      url: /senior-analyst-programme
  - title: Blog
    url: /blog
  - title: Join us
    url: /join-us
    button: true
  section1:
    title: We empower students
    subtitle: to make change through finance
    tiles:
    - title: Learn ESG Investing
      icon: school-outline
      text: We train a select group of analysts every semester
      url: /programmes-overview
      buttonText: Learn more
    - title: Support Innovation
      icon: globe
      text: Make real-world impact with real investments
      url: /philosophy
      buttonText: Learn more
    - title: Finance Change
      icon: star-outline
      text: All our profits go to charities and community projects
      url: /social-impact
      buttonText: Learn more
  section2:
    title: What is ESG investing?
    subtitle:
    features:
    - title: Environmental
      text: Here we assess to what extent a company’s operations impact the environment. We consider factors such as waste management, carbon footprint and the use of natural resources.
      # Icon (from /images/illustrations/icons/___.png)
      icon: E
    - title: Social
      text: Here we focus on how a company impacts communities at all levels. Does their business model have negative social externalities? Are they helping to improve the quality of life of people around the world?
      icon: S
    - title: Governance
      text: Here we address the leadership and management of a business. How does a company address diversity and inclusion? Are they transparent on executive pay and incentives?
      icon: G
  section3:
    title: Meet like-minded people
    subtitle: join the community
    image: pinboard.png
    buttonText: Meet the team
    buttonLink: "/team"
  section4:
    title: Don't just take our word for it
    subtitle: Here is what some of our former analysts had to say
    clients:
    - name: Conan Phimister
      quote: One of the best things about Prosper was the exposure to people within the finance industry trying to push socially responsible finance forward
      job: Analyst, 18/19 Sem 1
      img: Conan.jpg
    - name: Melissa Fasol
      quote: The Prosper community is diverse in culture and academic background – everyone is welcome and equally able to make a valuable contribution
      job: Analyst, 18/19 Sem 1
      img: Melissa.jpg
    - name: Donald Toperesu
      quote: Working with analysts from different cultural and racial backgrounds was also enlightening as I got to learn new concepts and improve my critical thinking skills
      job: Analyst, 19/20 Sem 1
      img: Donald.jpg
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: logo-full.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://facebook.com/prospersocialfinance/
      # Icons are from Font Awesome
      icon: facebook
    - link: https://instagram.com/prospersocialfinance
      icon: instagram
    - link: https://twitter.com/prospersocfin
      icon: twitter
    - link: https://www.linkedin.com/company/prospersocialfinance/
      icon: linkedin
    - link: https://www.youtube.com/channel/UC3zBvpY_n0QkSxrAatTSPLg/
      icon: youtube-play
    bulmalogo: false
    quicklinks:
      column1:
        title: "About"
        links:
        - text: Overview
          link: /about
        - text: Mission & Values
          link: /mission
        - text: Our Team
          link: /team
      column2:
        title: "Programmes"
        links:
        - text: Overview
          link: /programmes-overview
        - text: Analysts
          link: /training
        - text: Senior Analysts
          link: /senior-analyst-programme
